# Generated by Django 3.0.6 on 2020-05-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20200515_2340'),
        ('post', '0002_auto_20200518_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_profile.UserProfile'),
        ),
    ]
