# Generated by Django 3.0.6 on 2020-05-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200520_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
