# Generated by Django 3.0.6 on 2020-05-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200520_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
